version: '3'
services:
  postgresql:
    image: postgres:11.3
    container_name: postgres_testing_proyecto_b
    ports:
    - 5432
    env_file:
      - ./.env
    volumes:
    - postgresql_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/bproject
      - bundler_gems:/usr/local/bundle/
      - yarn_packages:/bproject/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
volumes:
  postgresql_data: 
  bundler_gems:
  yarn_packages: